---
- name: Check if Singularity is installed and its version
  command: "dpkg-query -W -f='${Version}' singularity-ce"
  register: installed_version
  ignore_errors: true
  changed_when: false
  when: installed_version is not defined  # Only execute if the package is not installed

- name: Get system architecture
  command: "dpkg --print-architecture"
  register: system_architecture
  changed_when: false

- name: Download Singularity deb package
  get_url:
    url: "{{ singularity_deb_url }}"
    dest: "/tmp/{{ singularity_deb_file }}"
  when: expected_version != installed_version.stdout | default('') and system_architecture.stdout == 'amd64'

- name: Install Singularity
  apt:
    deb: "/tmp/{{ singularity_deb_file }}"
  when: expected_version != installed_version.stdout | default('') and system_architecture.stdout == 'amd64'

- name: Cleanup deb file
  file:
    path: "/tmp/{{ singularity_deb_file }}"
    state: absent
  when: expected_version != installed_version.stdout | default('') and system_architecture.stdout == 'amd64'
