---
- name: create config dir
  file:
    path: "{{ nginx_config_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: install monior config file
  copy:
    src: "default.conf"
    dest: "{{ nginx_config_dir }}/default.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: install systemd unit file
  template:
    src: templates/docker.nginx.service.j2
    dest: "/etc/systemd/system/{{ nginx_svc_name }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: configure service
  systemd:
    name: "{{ nginx_svc_name }}"
    state: "{{ nginx_state }}"
    enabled: "{{ nginx_enabled }}"
    daemon_reload: yes
  notify: restart nginx
