---
- name: Common set up
  hosts: all
  become: true
  become_user: root
  roles:
    - hosts
    - utilities
    - nextflow
    - mambaorg.micromamba
    - geerlingguy.docker
    - prometheus-node-exporter
    - abims_sbr.singularity
    - role: nis
      NIS_MASTER: "{{groups.slurm_master[0]}}"

- name: Slurm master
  hosts: slurm_master
  become: true
  become_user: root
  roles:
      - slurm-master
      - prometheus-slurm-exporter
      - prometheus
      - grafana
      # - alertmanager
      - rsyslog_server
      - nextflow-demo
      - role: 'nfs-server'
        NFS_EXPORTS:
          - path: '/home/'
            clients: "{{groups.slurm_worker + groups.slurm_submit|default([])}}"
  tasks:
    - service:
        name=slurmctld
        state=restarted
      when: 'is_debian_compatible and (is_debian_8_or_later or is_ubuntu_15_10_or_later)'

- name: Slurm worker
  hosts: slurm_worker
  become: true
  become_user: root
  roles:
    - server-code
    - slurm-worker
    - rsyslog_client
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
  tasks:
    - service:
        name=slurmd
        state=restarted
      when: 'is_debian_compatible and (is_debian_8_or_later or is_ubuntu_15_10_or_later)'
    - service:
        name=slurm-llnl
        state=restarted
      when: 'is_debian_compatible and not (is_debian_8_or_later or is_ubuntu_15_10_or_later)'
    - service:
        name=slurmd
        state=restarted
      when: is_rhel7_compatible
    - service:
        name=slurm
        state=restarted
      when: is_rhel6_compatible
