---
- name: Common set up
  hosts: all
  become: true
  become_user: root
  roles:
    - hosts
    - utilities
    - nextflow
    - mambaorg.micromamba
    - geerlingguy.docker
    - abims_sbr.singularity
    - s3storage
