---
- name: Common set up
  hosts: all
  become: yes
  become_user: root
  roles:
    - hosts
    - role: 's3storage'
      S3_MOUNTS:
        - fs: "project1"
    - nextflow
    - anaconda
    - singularity


- name: Slurm master
  hosts: slurm_master
  become: yes
  become_user: root
  roles:
    - slurm-master
    - nextflow-demo
    - role: 'nfs-server'
      NFS_EXPORTS:
        - path: '/home/'
          clients: "{{groups.slurm_worker + groups.slurm_submit|default([])}}"


- name: Slurm worker
  hosts: slurm_worker
  become: yes
  become_user: root
  roles:
    - slurm-worker
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'

