- name: Install latest version code-server
  tags:
    - slurm
  shell: |
    curl -fsSL https://code-server.dev/install.sh | sh

- name: Create common_jobs folder if not exists
  file:
    path: /opt/common_jobs
    state: directory
    mode: 0755
    owner: root
    group: root
    
- name: Add sbatch job for code-server
  copy:
    src: code-server-sbatch.sh
    dest: /opt/common_jobs/code-server-sbatch.sh
    mode: 0755