---
- name: restart slurm-exporter
  service:
    name: "{{ slurm_exporter_svc_name }}"
    state: restarted

- name: restart grafana
  service:
    name: "{{ grafana_svc_name }}"
    state: restarted
  failed_when: false
