---
- name: Create sample nextflow demo run
  copy:
    src: "fetchngs"
    dest: "/home/{{ansible_user}}/"
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Ensure the nextflow directory exists
  file:
    path: "/home/{{ansible_user}}/.nextflow"
    state: directory
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"