---
- name: add cgroups to grub options
  lineinfile:
    dest: /etc/default/grub
    insertafter: '^GRUB_CMDLINE_LINUX=[^\\$]'
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} cgroup_enable=memory swapaccount=1"'
  register: update_grub

- name: update grub
  block:
    - name: update grub
      command: update-grub
      register: update_grub_cmd
      changed_when: update_grub_cmd.rc == 0
    - name: reboot after updating grub config
      reboot:
        reboot_timeout: "{{ slurm_node_reboot_timeout }}"
  when: update_grub.changed and ansible_os_family == "Debian"
- name: Deploy SLURM cgroup configuration file (main)
  copy:
    src: '{{ slurm_cgroup_conf_file }}'
    dest: '/etc/slurm/cgroup.conf'
    mode: 0444
    owner: root
    group: root
