---
- include_tasks: user_and_group.yml

- name: Create slurm directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ slurm_username }}"
  with_items:
    - "{{ slurm_build_dir }}"
    - "{{ slurm_conf_dir }}"
    - "{{ slurm_log_dir }}"
    - "{{ slurm_spool_dir }}"
    - "{{ slurm_state_save_location }}"

- include_tasks: cgroup.yml
- include_tasks: slurm.yml
