---

- name: install slurm dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - fakeroot
    - devscripts
    - equivs
    - libmunge-dev
    - munge # install to fix check for munge
    - libpam0g-dev
    - libdbus-1-dev
    - libev-dev
    - libevent-dev
    - zlib1g
    - zlib1g-dev
    - pandoc

- name: download slurm source
  get_url:
    url: "https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2"
    dest: "/tmp/slurm-{{ slurm_version }}.tar.bz2"
    mode: 0644
  when: slurm_version is defined

- name: extract slurm source
  become: true
  become_user: root
  unarchive:
    src: "/tmp/slurm-{{ slurm_version }}.tar.bz2"
    dest: "/tmp"
    remote_src: yes
  when: slurm_version is defined

- name: configure slurm manually
  shell: "cd {{ slurm_build_dir }} && {{ slurm_configure }}"
  when: slurm_version is defined and slurm_gpu is not defined


- name: configure slurm with nvml
  shell: "cd {{ slurm_build_dir }} && {{ slurm_configure_nvml }}"
  when: slurm_version is defined and slurm_gpu is defined

- name: build slurm
  shell: "cd {{ slurm_build_dir }} && make -j$(nproc) install"
  become: true
  become_user: root
  when: slurm_version is defined

- name: update ld cache
  command: ldconfig -n {{ slurm_install_prefix }}/lib

- name: copy service files
  copy:
    src: "{{ slurm_build_dir }}/etc/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    remote_src: yes
    mode: "0644"
  with_items:
    - slurmctld.service
    - slurmd.service

- include_tasks: cgroup.yml

- name: add slurm and cgroup configuration
  template:
    src: "{{ slurm_conf_template }}"
    dest: "/etc/slurm/slurm.conf"
    mode: "0644"

- name: add gres configuration
  template:
    src: "{{ slurm_gres_conf_template }}"
    dest: "/etc/slurm/gres.conf"
    mode: "0644"
  when: slurm_gpu is defined

- name: start slurmctl and slurmd
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - slurmctld
    - slurmd
