---

- name: Set variables (Debian/Ubuntu)
  set_fact:
    slurm_db_server_name: MariaDB
    slurm_db_server_pkg: mariadb-server
    slurm_db_python_pkg: python3-mysqldb
    slurm_db_service_name: mysql
    mysql_cnf_path: '/etc/mysql/my.cnf'
  when: 'is_debian_or_ubuntu and (is_debian_8_or_later or is_ubuntu_14_04_or_later)'

- name: Set variables (older Debian/Ubuntu)
  set_fact:
    slurm_db_server_name: MySQL
    slurm_db_server_pkg: mysql-server
    slurm_db_python_pkg: python-mysqldb
    slurm_db_service_name: mysql
    mysql_cnf_path: '/etc/mysql/my.cnf'
  when: 'is_debian_or_ubuntu and not (is_debian_8_or_later or is_ubuntu_14_04_or_later)'

- name: Set variables (RHEL 7.x)
  set_fact:
    slurm_db_server_name: MariaDB
    slurm_db_server_pkg: mariadb-server
    slurm_db_python_pkg: MySQL-python
    slurm_db_service_name: mariadb
    mysql_cnf_path: '/etc/my.cnf'
  when: 'is_rhel7_compatible'

- name: Set variables (RHEL 6.x)
  set_fact:
    slurm_db_server_name: MySQL
    slurm_db_server_pkg: mysql-server
    slurm_db_python_pkg: MySQL-python
    slurm_db_service_name: mysqld
    mysql_cnf_path: '/etc/my.cnf'
  when: 'is_rhel6_compatible'


- name: Install {{slurm_db_server_name}}, used for SLURM accounting
  tags:
    - slurm
    - slurmdbd
  package:
    name:
      - '{{slurm_db_server_pkg}}'
      - '{{slurm_db_python_pkg}}'
    state: '{{ pkg_install_state }}'


- name: Ensure InnoDB parameters are large enough for SLURM DBD
  tags:
    - slurm
    - slurmdbd
  blockinfile:
    path: '{{ mysql_cnf_path }}'
    state: present
    backup: yes
    insertafter: EOF
    content: |

      # See https://wiki.fysik.dtu.dk/niflheim/Slurm_database#id5
      [mysqld]
      innodb_buffer_pool_size=1024M
      innodb_log_file_size=64M
      innodb_lock_wait_timeout=900


- name: Ensure {{slurm_db_server_name}} daemon is up
  tags:
    - slurm
    - slurmdbd
  service:
    name: '{{slurm_db_service_name}}'
    enabled: yes
    state: started


- name: Create DB for SLURMDBD
  tags:
    - slurm
    - slurmdbd
  # NOTE: the `SLURM_ACCOUNTING_*` variables are defined in `roles/slurm-common/defaults`
  mysql_db:
    name: '{{SLURM_ACCOUNTING_DB_NAME}}'
    state: present


- name: Create DB user for SLURMDBD
  tags:
    - slurm
    - slurmdbd
  # NOTE: the `SLURM_ACCOUNTING_*` variables are defined in `roles/slurm-common/defaults`
  mysql_user:
    name: '{{SLURM_ACCOUNTING_DB_USER}}'
    host: '{{item}}'
    password: '{{SLURM_ACCOUNTING_DB_PASS}}'
    priv: '{{SLURM_ACCOUNTING_DB_NAME}}.*:ALL'
    state: present
  loop:
    - '{{SLURM_ACCOUNTING_HOST}}'
    - 'localhost'
