---
#
# Variables for installing Anaconda Python.
# All the values are derived from the constants defined in `defaults/main.yml`
#
anaconda_name : 'Anaconda{{anaconda_python_version}}-{{anaconda_version}}-{{anaconda_platform}}'
anaconda_installer_sh : '{{ansible_env.TMPDIR|default("/var/tmp")}}/{{anaconda_name}}.sh'
anaconda_installer_url : '{{anaconda_mirror}}/{{anaconda_name}}.sh'
anaconda_platform : 'Linux-{{ansible_architecture}}'
# anaconda_platform: 'Linux-arm64'
anaconda_home: '{{anaconda_location}}/{{anaconda_name}}'
is_slurm_master: '{{ ansible_hostname == slurm_master }}'