- name: Check if nextflow already exists
  stat:
    path: "/opt/nextflow/v_{{ nextflow_version }}/nextflow"
  register: nextflow_file

- name: Remove nextflow directory if nextflow file doesn't exist
  file:
    path: /opt/nextflow
    state: absent
  when: not nextflow_file.stat.exists

- name: Create nextflow directory if it doesn't exist
  file:
    path: /opt/nextflow
    state: directory
    mode: 0755
    owner: root
    group: root
  when: not nextflow_file.stat.exists

- name: Create directory for Nextflow version if it doesn't exist
  file:
    path: "/opt/nextflow/v_{{ nextflow_version }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: not nextflow_file.stat.exists
  
- name: Download nextflow container if not already downloaded
  when: not nextflow_file.stat.exists
  get_url:
    url: "https://github.com/nextflow-io/nextflow/releases/download/v{{ nextflow_version }}/nextflow-{{ nextflow_version }}-all"
    dest: "/opt/nextflow/v_{{ nextflow_version }}/nextflow"
    mode: 0755
    owner: root
    group: root

- name: Make nextflow match in $PATH
  template:
    src: "nextflow.sh.j2"
    dest: "/etc/profile.d/nextflow.sh"
    mode: 0444
    owner: root
    group: root

- name: Create Nextflow directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '1777'
  loop: "{{ nextflow_directories }}"

- name: Add config nextflow
  copy:
    src: "config"
    dest: "{{ nextflow_cache_dir }}"
    owner: root
    group: root
    mode: '1777'
