---
- name: Create `slurm` system group
  group:
    name: slurm
    system: yes
  tags:
    - slurm

- name: Create `slurm` system user
  user:
    name: slurm
    group: slurm
    system: yes
  tags:
    - slurm

- name: Create work directory {{item}}
  file:
    path: '{{item}}'
    state: directory
    owner: slurm
    group: slurm
  loop:
    - /etc/slurm-llnl
    - /var/log/slurm
    - /var/run/slurm
    - /var/spool/slurm
  tags:
    - slurm

- import_tasks: munge.yml

- name: Deploy SLURM configuration file
  tags:
    - slurm
  template:
    src: '{{ slurm_conf_file|default("slurm.conf.j2") }}'
    dest: '/etc/slurm-llnl/slurm.conf'
    owner: root
    group: root
    mode: 0444