---

- name: ensure {{fs.mountpoint}} directory exists
  file:
    path={{fs.mountpoint}}
    state=directory
  when: not ansible_check_mode
  
- name: add to /etc/fstab
  become: true
  become_user: root
  mount:
    name='{{fs.mountpoint}}'
    src='{{fs.fs}}'
    fstype=nfs
    opts='{{fs.options|default("rw,async")}}'
    state='{{fs.state|default("mounted")}}'

- name: Allow NFS homes through SELinux
  command: |
    setsebool -P use_nfs_home_dirs=1
  when: 'fs.mountpoint == "/home" and is_rhel_compatible and ansible_selinux.status == "enabled"'
