is_slurm_master: '{{ ansible_hostname == slurm_master }}'
nextflow_base: "{{ '/data' if nextflow_base_dir is not defined else nextflow_base_dir }}"
nextflow_cache_dir: "{{ nextflow_base }}/nextflow/.nextflow_cache"
nextflow_conda_cache_dir: "{{ nextflow_base }}/nextflow/.conda_cache"
nextflow_singularity_cache_dir: "{{ nextflow_base }}/nextflow/.singularity_cache"
nextflow_singularity_lib_dir: "{{ nextflow_base }}/nextflow/.singularity_lib"
nextflow_directories:
  - "{{ nextflow_base }}/nextflow"
  - "{{ nextflow_cache_dir }}"
  - "{{ nextflow_conda_cache_dir }}"
  - "{{ nextflow_singularity_cache_dir }}"
  - "{{ nextflow_singularity_lib_dir }}"
