version: '3'
services:
  minio:
    image: 'minio/minio:latest'
    ports:

      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    command: server /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc alias set myminio http://minio:9000 root password;
        /usr/bin/mc mb -p myminio/project1;
        /usr/bin/mc anonymous set public myminio/project1;
        exit 0;
      "