- name: Determine architecture
  set_fact:
    architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

- name: Check if Goofys directory already exists
  stat:
    path: "/opt/goofys_{{ goofys_version }}"
  register: goofys_directory

- name: Create the Goofys directory if it doesn't exist
  file:
    path: "/opt/goofys_{{ goofys_version }}"
    state: directory
    mode: 0755
  when: not goofys_directory.stat.exists

- name: Clone Goofys repository if it doesn't exist
  git:
    repo: "https://github.com/giangbioinformatics/goofys-S3-fuse-v{{ goofys_version }}.git"
    dest: "/opt/goofys_{{ goofys_version }}"
    update: no
  when: not goofys_directory.stat.exists

- name: Compile Goofys using Go if it was cloned
  shell: |
    source /etc/profile.d/golang.sh
    cd "/opt/goofys_{{ goofys_version }}"
    GOOS=linux GOARCH={{ architecture }} go build -buildvcs=false
  args:
    executable: /bin/bash

- name: Create template to get source for Goofys
  template:
    src: 'goofys.sh.j2'
    dest: '/etc/profile.d/goofys.sh'
    mode: 0444
    owner: root
    group: root

- name: Ensure the directory exists for mounting S3 storage
  file:
    path: "/root/.aws"
    state: directory
    mode: 0755
  tags: s3storage

- name: Create template for mounting S3 storage
  template:
    src: 'credentials.j2'
    dest: '/root/.aws/credentials'
    mode: 0444
    owner: root
    group: root
  tags: s3storage

- name: Mount S3 storage using Goofys
  include_tasks: s3mount.yml
  vars:
    fs: '{{ item }}'
  loop: '{{ S3_MOUNTS }}'
  tags: s3storage
  when: mount_s3_storage == true
