
- name: Ensure {{ s3_project_mount_point }}/{{ fs.fs }} directory exists
  file:
    path="{{ s3_project_mount_point }}/{{ fs.fs }}"
    state=directory

- name: Add to fstab
  lineinfile:
    path: /etc/fstab
    line: "/opt/goofys_{{ goofys_version }}/goofys#{{ fs.fs }} {{s3_project_mount_point}}/{{ fs.fs }} fuse _netdev,allow_other,--file-mode=0666,--dir-mode=0777,--endpoint={{s3_url}} 0 0"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644

- name: Reload fstab
  command: mount -a