
---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

    
- name: Add the inventory into /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{item}}"
    state: present
  when: hostvars[item]['ansible_facts']['default_ipv4'] is defined
  with_items:
    - "{{ groups['all'] }}"