VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "bento/ubuntu-20.04"
PROVIDER="vmware_desktop"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_IMAGE
  config.vm.box_download_insecure = true
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.define "controller" do |login|
    login.vm.hostname = "controller"
    login.vm.network :private_network, ip: "192.168.58.10"
    login.vm.provider PROVIDER do |v|
      v.memory = 2048
      v.cpus = 4
      v.ssh_info_public = true
      v.linked_clone = false
      v.gui = true
      v.vmx["ethernet0.virtualdev"] = "vmxnet3"
      v.vmx["ethernet0.pcislotnumber"] = "33"
    end
  end
  config.vm.define "worker" do |login|
    login.vm.hostname = "worker"
    login.vm.network :private_network, ip: "192.168.58.11"
    login.vm.provider PROVIDER do |v|
      v.memory = 2048
      v.cpus = 2
      v.ssh_info_public = true
      v.linked_clone = false
      v.gui = true
      v.vmx["ethernet0.virtualdev"] = "vmxnet3"
      v.vmx["ethernet0.pcislotnumber"] = "33"
    end
  end
end